# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CHARGER_LN8000)	+= ln8000_charger.o
obj-$(CONFIG_CHARGER_LN8000_MUNCH)	+= ln8000_charger_munch.o
obj-$(CONFIG_CHARGER_LN8000_PSYCHE)    += ln8000_charger_psyche.o
obj-$(CONFIG_LN8282)	+= ln8282.o
