# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_RX1619)		+= rx1619.o
obj-$(CONFIG_RX1619_CAS)		+= rx1619_cas.o
obj-$(CONFIG_RX1619_TRIM)	+= rx1619_trim.o
obj-$(CONFIG_RX1619_TRIM_CAS)	+= rx1619_trim_cas.o
