#
# Makefile for the Novatek NT36523 touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_NT36523_HOSTDL_SPI) += nt36523_touch.o
nt36523_touch-y := nt36xxx.o \
	nt36xxx_fw_update.o \
	nt36xxx_ext_proc.o \
	nt36xxx_mp_ctrlram.o
