obj-$(CONFIG_TOUCHSCREEN_FOCALTECH) += focaltech_touch.o
focaltech_touch-y := focaltech_core.o \
                     focaltech_ex_fun.o \
                     focaltech_ex_mode.o \
                     focaltech_gesture.o \
                     focaltech_esdcheck.o \
                     focaltech_spi.o \
                     focaltech_point_report_check.o \
                     focaltech_flash.o \
                     focaltech_flash/focaltech_upgrade_ft3658u.o \
                     focaltech_test/focaltech_test.o \
                     focaltech_test/focaltech_test_ini.o \
                     focaltech_test/supported_ic/focaltech_test_ft3658u.o
