#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC)	+= fpc/
obj-$(CONFIG_FINGERPRINT_FPC_FOD)	+= fpc_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX)	+= goodix/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
