name: Build KSUD
on:
  push:
    branches: [ "main", "ci" ]
    paths: 
      - '.github/workflows/build-ksud.yml'
      - '.github/workflows/ksud.yml'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/build-ksud.yml'
      - '.github/workflows/ksud.yml'
      - 'userspace/ksud/**'
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android
          - target: x86_64-pc-windows-gnu # only for build
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
