# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PD_POLICY_MANAGER)		+= pd_policy_manager.o cp_qc30.o
obj-$(CONFIG_PD_POLICY_MANAGER_DAGU)		+= pd_policy_manager_dagu.o cp_qc30_dagu.o
obj-$(CONFIG_PD_POLICY_MANAGER_MUNCH)		+= pd_policy_manager_munch.o cp_qc30_munch.o
obj-$(CONFIG_PD_POLICY_MANAGER_PSYCHE)		+= pd_policy_manager_psyche.o cp_qc30_psyche.o
obj-$(CONFIG_BQ2597X_CHARGE_PUMP)	+= bq2597x_charger.o
obj-$(CONFIG_BQ2597X_CHARGE_PUMP_DAGU)	+= bq2597x_charger_dagu.o
obj-$(CONFIG_BQ_PUMP_WIRELESS_CHARGE)	+= wireless_bq_dc_charge.o
obj-$(CONFIG_BQ2597X_CHARGE_PUMP_STANDALONE_MUNCH)	+= bq2597x_charger_munch.o
obj-$(CONFIG_CHARGER_BQ25790)		+= bq25790_charger.o
