# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_ONEWIRE_GPIO) += onewire_gpio.o
obj-$(CONFIG_BATT_VERIFY_BY_DS28E16) += onewire_gpio.o ucl_sha3.o sha384_software.o ds28e16.o
obj-$(CONFIG_WATCHDOG_MAX28200)		+= max28200.o
obj-$(CONFIG_CP_MAX77932)		+= max77932.o
