obj-$(CONFIG_TOUCHSCREEN_ST_FTS_V521_SPI) := fts_touch_spi.o
fts_touch_spi-y := fts_lib/ftsCompensation.o \
		fts_lib/ftsCore.o \
		fts_lib/ftsError.o \
		fts_lib/ftsFrame.o \
		fts_lib/ftsIO.o \
		fts_lib/ftsTest.o \
		fts_lib/ftsTool.o \
		fts_lib/ftsFlash.o \
		fts_lib/ftsGesture.o \
		fts_proc.o \
		fts.o
