# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_QPNP_SMB5_CAS)		+= step-chg-jeita.o battery.o qpnp-smb5.o smb5-lib.o pmic-voter.o storm-watch.o schgm-flash.o
obj-$(CONFIG_SMB1398_CHARGER_CAS)		+= smb1398-charger.o pmic-voter.o
obj-$(CONFIG_FUEL_GAUGE_BQ28Z610)       += bq27z561_fg.o
