name: Kernel Build (Apollo)

on:
  workflow_dispatch:
    inputs:
      KERNEL_TREE:
        description: "Kernel Tree"
        default: "https://github.com/Impqxr/kernel_xiaomi_sm8250"
        required: true
      KERNEL_TREE_BRANCH:
        description: "Kernel Tree Branch"
        required: true
        default: "base"

      KERNELSU_SETUP_URL:
        description: "KernelSU setup.sh URL (empty it to disable)"
        required: false
        default: "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/refs/heads/dev/kernel/setup.sh"
      KERNELSU_SETUP_BRANCH:
        description: "KernelSU Branch"
        required: false
        default: "legacy"
      KERNELSU_PATCHES:
        description: "Patches for KernelSU. Urls leading to .patch file which are split by comma"
        required: false
        default: ""

      ANYKERNEL_URL:
        description: "AnyKernel URL (empty it to disable)"
        default: "https://github.com/Impqxr/AKapollo"
        required: false
      ANYKERNEL_BRANCH:
        description: "AnyKernel Branch"
        default: "main"
        required: false
      ANYKERNEL_ZIP_NAME:
        description: "File name (without .zip extension)"
        default: "N0Kernel-apollo"
        required: false

      CLANG_DOWNLOAD_URL:
        description: "Clang download url"
        default: "https://github.com/Impqxr/aosp_clang_ci/releases/download/13289611/clang-13289611-linux-x86.tar.xz"
        required: true

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Display Inputs
        run: |
          echo "::group::Inputs"
          echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
          echo "KernelSU Setup URL": ${{ github.event.inputs.KERNELSU_SETUP_URL }}
          echo "KernelSU Branch": ${{ github.event.inputs.KERNELSU_SETUP_BRANCH }}
          echo "KernelSU Patches": ${{ github.event.inputs.KERNELSU_PATCHES }}
          echo "AnyKernel URL: ${{ github.event.inputs.ANYKERNEL_URL }}/tree/${{ github.event.inputs.ANYKERNEL_BRANCH }}"
          echo "::endgroup::"

      - name: Cache Clang
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: clang
          key: clang-ci
          restore-keys: |
            clang-

      - name: Download and Extract Clang (if not cached)
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          wget "${{ github.event.inputs.CLANG_DOWNLOAD_URL }}" -O clang.tar.gz
          mkdir -p clang
          tar -xf clang.tar.gz -C clang

          # extract toolchain from the parent directory (if exists)
          cd clang
          if [ -d clang-* ]; then
            mv clang-*/* .
          fi
          cd ..

          rm clang.tar.gz

      - name: Initialize workspace
        run: |
          echo "tools_folder=$(pwd)" >> $GITHUB_OUTPUT
          git clone --depth=1 "${{ github.event.inputs.KERNEL_TREE }}" -b "${{ github.event.inputs.KERNEL_TREE_BRANCH }}" kernel_tree
          echo "kernel_folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
        id: workspace

      - name: Building kernel
        run: |
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="${{ github.actor }}"
          export KBUILD_BUILD_HOST="github.com"

          if [[ -n "${{ github.event.inputs.KERNELSU_SETUP_URL }}" && -n "${{ github.event.inputs.KERNELSU_SETUP_BRANCH }}" ]]; then
            curl -LSs "${{ github.event.inputs.KERNELSU_SETUP_URL }}" | bash -s ${{ github.event.inputs.KERNELSU_SETUP_BRANCH }}
            if [ -n "${{ github.event.inputs.KERNELSU_PATCHES }}" ]; then
              cd Kernel*
              echo "${{ github.event.inputs.KERNELSU_PATCHES }}" | tr ',' '\n' | while read -r PATCH; do
                TRIMMED=$(echo "$PATCH" | xargs)
                TEMP_PATCH_FILE="/tmp/downloaded_patch_$(date +%s%N).patch"
                curl -fsSL "$TRIMMED" -o "$TEMP_PATCH_FILE"
                patch -p1 < "$TEMP_PATCH_FILE"
              done
              cd ..
            fi
          fi

          make O=out vendor/apollo_defconfig PATH="${{ steps.workspace.outputs.tools_folder }}/clang/bin:$PATH"
          make O=out CC=clang -j$(nproc --all) PATH="${{ steps.workspace.outputs.tools_folder }}/clang/bin:$PATH" CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
        working-directory: ${{ steps.workspace.outputs.kernel_folder }}

      - name: "Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/Image.gz
      - name: "Upload dtb"
        uses: actions/upload-artifact@v4
        with:
          name: dtb
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/dtb.img
      - name: "Upload dtbo.img (AOSP)"
        uses: actions/upload-artifact@v4
        with:
          name: dtbo.img
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/dtbo.img

      - name: AnyKernel3
        if: ${{ success() && github.event.inputs.ANYKERNEL_URL != '' && github.event.inputs.ANYKERNEL_BRANCH != '' && github.event.inputs.ANYKERNEL_ZIP_NAME != '' }}
        run: |
          git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b ${{ github.event.inputs.ANYKERNEL_BRANCH }} AnyKernel3
          if [ -e "Image.gz" ]; then
            cp -f Image.gz AnyKernel3
          fi
          if [ -e "dtb.img" ]; then
            cp -f dtb.img AnyKernel3/dtb
          fi
          if [ -e "dtbo.img" ]; then
            cp -f dtbo.img AnyKernel3
          fi
          cd AnyKernel3
          zip -q -r "${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}.zip" *
          mv "${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}.zip" ../
        working-directory: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/
      - name: "Upload AnyKernel"
        uses: actions/upload-artifact@v4
        if: ${{ success() && github.event.inputs.ANYKERNEL_URL != '' && github.event.inputs.ANYKERNEL_BRANCH != '' && github.event.inputs.ANYKERNEL_ZIP_NAME != '' }}
        with:
          name: ${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}
          path: |
            ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/
            !${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/.git
            !${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/.github
