name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target device'
        required: true
        default: 'alioth'
        type: choice
        options:
          - 'alioth'
          - 'pipa'
      system_version:
        description: 'Target System'
        required: true
        type: choice
        default: 'miui'
        options:
          - 'aosp'
          - 'miui'
          - 'all'

      kernelsu_version:
        description: 'KernelSU Version'
        required: true
        type: choice
        default: 'sukisu-ultra'
        options:
          - 'sukisu-ultra'
          - 'ksu'
          - 'rksu'
          - 'sukisu'
          - 'noksu'

      additional_function:
        description: 'Additional Functions'
        required: true
        type: choice
        default: 'no'
        options:
          - 'no'
          - 'susfs-kpm'
          - 'susfs'
          - 'kpm'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Kernel Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y \
          build-essential git curl wget bison flex zip bc \
          cpio libssl-dev libncurses-dev gcc \
          python3 python3-pip ccache
          sudo apt update
          sudo apt install -y software-properties-common
          apt policy python2
          sudo apt install -y python2
          python2 --version
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2.7 get-pip.py
          pip2.7 --version
            

      - name: Cache AOSP Clang
        uses: actions/cache@v4
        id: clang-cache
        with:
          path: toolchain/clang-13289611
          key: ${{ runner.os }}-aosp-clang-13289611

      - name: Download and Extract AOSP Clang
        if: steps.clang-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p toolchain/clang-13289611
          wget -O clang.tar.xz https://github.com/Impqxr/aosp_clang_ci/releases/download/13289611/clang-13289611-linux-x86.tar.xz
          tar -xJf clang.tar.xz -C toolchain/clang-13289611 --strip-components=1
          rm -f clang.tar.xz
          
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache_mikernel
          key: ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-

      - name: Build Kernel
        run: |
          sed -i 's|TOOLCHAIN_PATH=\$HOME/toolchain/clang-13289611/bin|TOOLCHAIN_PATH=$(pwd)/toolchain/clang-13289611/bin|' build.sh
          DEVICE="${{ github.event.inputs.target_device }}"
          SYSTEM="${{ github.event.inputs.system_version }}"
          KSU_VERSION="${{ github.event.inputs.kernelsu_version }}"
          ADDITIONAL_FUNCTION="${{ github.event.inputs.additional_function }}"
          bash build.sh "$DEVICE" "$KSU_VERSION" $ADDITIONAL_FUNCTION "$SYSTEM"

      - name: Set Kernel Path
        run: |
          if [[ "${{ github.event.inputs.system_version }}" == "aosp" || "${{ github.event.inputs.system_version }}" == "miui" ]]; then
          KernelPath=$(ls N0Kernel_*.zip 2>/dev/null | head -n 1 || true)
          echo "KernelPath=$(pwd)/$KernelPath" >> $GITHUB_ENV
          else
          tar -czvf Kernel_All.tar.gz N0Kernel_*.zip
          echo "KernelPath=$(pwd)/Kernel_All.tar.gz" >> $GITHUB_ENV
          fi

     # - name: Upload Kernel to Telegram
       # run: |
        #  curl -F chat_id=${{ secrets.TG_CHAT_ID }} \
             #  -F document=@${{ env.KernelPath }} \
             #  "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument"
      
      - name: Upload Kernel to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.target_device }}-${{ github.event.inputs.system_version }}-${{ github.run_number }}
          name: Kernel ${{ github.event.inputs.target_device }} (${{ github.event.inputs.system_version }})
          files: ${{ env.KernelPath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
